package Songcalc;

/**
 * @author kemckai
 *
 */
import java.util.Scanner;
import java.util.*;
import java.awt.Container;
import java.io.*;
import java.util.Random;
public class songEngine {

private static String Time[] = {"2/4","3/4"," 4/4","4/8","6/8"};
private static String Key[] = {"C","C#","D","Eb","E","F","F#","G","Ab","A","Bb","B"};
private static String songPart[] = {"Intro","Verse","Pre-Chorus","Chorus","Bridge","Interlude","Turn-around","Solo","Coda"};
private static String Mode [] = {"Ionian","Dorian","Phyrgian","Lydian", "Mixolydian","Aeolian", "Locrian"};
private static String songStructure[] = {"I	IV	V","i	bVII	bVI	","I	V	IV	V"," i		bVI",
"i	bVI	bVII"," i	bVI	bVII"," I	v	bVII", "I		bVII	IV", "IV		I	", "I		bVII	IV",
"iv		bIII	bVII"," i	bIII	bVI	iv"," i		IV	"," I	V	IV	"," I	IV	V	IV", "I	ii	vi	IV", 
"IV		I	", "I	IV	II	V"," bVI	bIII	bVII	IV"," V	I	ii	V"," I	IV	V	IV"," IV	ii	I	",
"i	bVII	bVI	bVII", "i	bIII	bVII	IV", "i		bVI	IV"," i	bVI	bIII	bVII"," i	bVII	bVI	V", 
"vi	V	IV	I"," I	V	ii	V"," i	bVII	bIII	bVI"," I	IV	V	", "i		bVI	bVII", 
"I	bVII	bIII	IV", "I	iii	vi	V", "I IV	I", "I	vi	IV	V", "I	ii	IV", "i	bIII	bVII	IV",
" I	bVII	IV	bVI"," I	V	IV	", "i		bVI	bVII"," I	V	vi	IV", "i		bVI	", "I		bIII	IV",
"I		IV	", "bIII	bVII	i	", "I	V	vi	IV", "i	bIII	bVII	iv"," i	bIII	bVI	V",
"i	bVII	bVI	bVII", "I	bIII	IV	I", "i		IV	", "I		IV	I"," I	bVII	IV	I",
" bVI	bVII	i	bVII", "IV	bII	I	", "I		iv	", "ii		V	", "I		IV	",
"i		bVII	", "i	bVI	bIII	bVII", "I		IV	"," I	bVII	IV	bIII", "I	vi	IV	V"};

public static Random rnd = new Random();
public void NewJFrame() {
    initComponents();
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Song Calculator", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica", 0, 18))); // NOI18N
    jPanel1.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N

    jButton1.setText("Write");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
            write(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(35, 35, 35)
            .addComponent(jButton1)
            .addContainerGap(277, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(44, 44, 44)
            .addComponent(jButton1)
            .addContainerGap(200, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
}// </editor-fold>//GEN-END:initComponents

private void setDefaultCloseOperation(int exitOnClose) {
	// TODO Auto-generated method stub
	
}

private Container getContentPane() {
	// TODO Auto-generated method stub
	return null;
}

private void pack() {
	// TODO Auto-generated method stub
	
}

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

private void write(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_write
    // TODO add your handling code here:
}//GEN-LAST:event_write





public static void main(String[] args) throws FileNotFoundException{
/*
        Scanner s = new Scanner(new File("/Users/juleswells/Documents/workspace/Songcalc/src/Songcalc/songstructure.txt"));
    	ArrayList<String> Structure = new ArrayList<String>();
    	while (s.hasNextLine()){
    		Structure.trimToSize();
    		Structure.add(s.nextLine());
    		Collections.shuffle(Structure);
    		
     }
    	s.close();
    	
*/
    	
    	 
    	    String randomKey = (Key[new Random().nextInt(Key.length)]);
    	    String randomTime = (Time[new Random().nextInt(Time.length)]);
		    String randomsongPart = (songPart[new Random().nextInt(songPart.length)]);
		    String randomMode = (Mode[new Random().nextInt(Mode.length)]);
		    String randomStructure = (songStructure[new Random().nextInt(songStructure.length)]);
		  

		        System.out.println(randomTime);
		        System.out.println(randomsongPart);
				System.out.println(randomKey);
				System.out.println(randomMode);
				System.out.println(randomStructure);
				
			
				 
				  
				 try {
			            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
			                if ("Nimbus".equals(info.getName())) {
			                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
			                    break;
			                }
			            }
			        } catch (ClassNotFoundException ex) {
			            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
			        } catch (InstantiationException ex) {
			            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
			        } catch (IllegalAccessException ex) {
			            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
			        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
			            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
			        }
			        //</editor-fold>

			        /* Create and display the form */
			        java.awt.EventQueue.invokeLater(new Runnable() {
			            public void run() {
			                new NewJFrame().setVisible(true);
			            }
			        });
			    }

			    // Variables declaration - do not modify//GEN-BEGIN:variables
			    private javax.swing.JButton jButton1;
			    private javax.swing.JPanel jPanel1;
			    // End of variables declaration//GEN-END:variables
					  


        
     }
     
     
     
     
    
    




	    			
	    			
	    			
	    
     
   
	

	